### ISSUE TITLE
I can't Install Gnome

### ISSUE THREAD

**Issue by grdo787** [nmilosev/crouton-fedora#1]
I get this went trying to start Gnome with the freonx command:

[sudo] password for fedora: 
xauth:  file /root/.serverauth.12558 does not exist

X.Org X Server 1.18.3
Release Date: 2016-04-04
X Protocol Version 11, Revision 0
Build Operating System:  4.4.6-301.fc23.x86_64 
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Tue May 3 16:13:13 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=2ca03ac3-9a45-1744-8edc-8783ffb547e4/PARTNROFF=1 hashtree=PARTUUID=2ca03ac3-9a45-1744-8edc-8783ffb547e4/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=b26f449adbde4e3d573b39e1feed433bd2bb3029 salt=1414b2fe8f4f62ca3883d5e39a4e4f8318c801eded9317751963d767bb78fdb8" noinitrd vt.global_cursor_default=0 kern_guid=2ca03ac3-9a45-1744-8edc-8783ffb547e4 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 04 May 2016  10:12:18PM
Build ID: xorg-x11-server 1.18.3-2.fc23 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Fri May 13 00:34:20 2016
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/root/.xinitrc: line 1: exec: startxfce4: not found
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.

Couldn't get a file descriptor referring to the console

**Comment by nmilosev** [comment]
Hello! Congrats on the first issue reported!

I'm guessing you tried to install GNOME by modifying the `install.sh` script for freonx. Anyway, you forgot to change your `xinit` file as described there. Don't worry it's easy to fix. Use your favorite text editor to edit the file `/root/.xinitrc` and change `exec startxfce4` to `exec gnome-session` and try again. GNOME should work fine after that. Report back if you have any issues.

Just one more question, did you use the new fast installer (from the tarball)? How did it work for you? Any issues?

Cheers.

**Comment by grdo787** [comment]
Hello,
Yes that was it, I changed it to `exec gnome-session` and it worked, thanks. The only issue I have seen is that the cursor is a little slow and unresponsive. But other than that all things had worked so far.
Yes, I used the new installer and the installation was really super fast and with no issues.

**Comment by nmilosev** [comment]
Great! Happy to hear it. You should tweak the touchpad settings to your liking from the GNOME settings. I will close the issue now, feel free to open another one if you have more questions. :)

Have fun!
