### ISSUE TITLE
wget no longer available

### ISSUE THREAD

**Issue by boydkelly** [nmilosev/crouton-fedora#11]
Hi,
Migrating to a new chromebook with Version 65.0.3319.0 (Official Build) dev (64-bit).  I get a wget not found error.  Seems that this is no longer available in chromeos and needs to be replaced with curl.

crouton-fedora-master/installer/main.sh: 16: crouton-fedora-master/installer/../installer/fedora/bootstrap: wget: not found

**Comment by king-bee2001** [comment]
I have this issue as well

**Comment by ghost** [comment]
Build the github project chromebrew. and then type: crew install wget.

**Comment by boydkelly** [comment]
This is really old.  The current version of crouton-fedora uses curl.
