### ISSUE TITLE
Installer hits 404 error

### ISSUE THREAD

**Issue by VhatAmI** [nmilosev/crouton-fedora#4]
~/Downloads $ sudo sh ./crouton-fedora-master/installer/main.sh -r fedora -t fedora -p /usr/local/crouton-fedora
WARNING: Signed boot verification is disabled; enabling it for security.
You can disable it again using: sudo crossystem dev_boot_signed_only=0
Installing fedora-x86_64 chroot to /usr/local/crouton-fedora/chroots/fedora

Getting Docker build from Fedora Koji buildsystem...

--2016-07-16 14:22:52--  https://kojipkgs.fedoraproject.org//work/tasks/6155/14516155/Fedora-Docker-Base-24-20160616.n.0.x86_64.tar.xz
Resolving kojipkgs.fedoraproject.org... 209.132.181.10
Connecting to kojipkgs.fedoraproject.org|209.132.181.10|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-16 14:22:55 ERROR 404: Not Found.

**Comment by nmilosev** [comment]
Hi! Thanks for reporting this.

Indeed, https://kojipkgs.fedoraproject.org//work/tasks/6155/14516155/Fedora-Docker-Base-24-20160616.n.0.x86_64.tar.xz is now 404. I guess that after some time the builds get deleted.

In the future you can fix this by modifying the `installer/fedora/defaults` file. Anyway, I just updated the link with the latest build, so please remove all the installation files and download the installer again.

Thanks for reporting!

Cheers!

**Comment by VhatAmI** [comment]
@nmilosev thanks so much! I got fedora up and running today. 

Couple questions, my trusty chroot seems to be fine, but my sana one hangs on black screen, I'm not too worried about it, gonna see if I can figure out how to fix it myself. 

In trusty on my chromebook I can hit ctrl + alt + shit and left or right arrow to swap between chrome os and trusty, this shortcut doesn't seem to work on fedora, besides logging out, is there a quick way to go back and forth between OSes ? 

Thanks again for the quick fix !

**Comment by nmilosev** [comment]
Sorry for the delay, I'm abroad. 

You can switch easily, there are instructions in the readme, FAQ section. :)

Glad it works for you. 

Cheers!
