### ISSUE TITLE
freonx no longer working

### ISSUE THREAD

**Issue by vlaero** [nmilosev/crouton-fedora#5]
This issue surfaced just over two weeks ago after applying package updates.
I imagine an xorg update might have changed some settings that were required for freonx to work.

Here's the screen output:
[fedora@localhost ~]$ freonx
chown: cannot access '/tmp/crouton-lock': No such file or directory
xauth:  file /home/fedora/.serverauth.14580 does not exist

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System:  4.6.3-300.fc24.x86_64 
Current Operating System: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Jul 20 21:06:48 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=262615b0-bac7-3e4e-b65e-2b994e7922e4/PARTNROFF=1 hashtree=PARTUUID=262615b0-bac7-3e4e-b65e-2b994e7922e4/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=a99508b17fc83cb4a00e6651bb9b61a4211a87fa salt=f62d45db5a1d57c86563b56fe01231cbb23af6d23214c1956a89d8a068ea79b9" noinitrd vt.global_cursor_default=0 kern_guid=262615b0-bac7-3e4e-b65e-2b994e7922e4 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic i915.enable_psr=1  
Build Date: 19 July 2016  06:08:11PM
Build ID: xorg-x11-server 1.18.4-1.fc24 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Wed Jul 27 23:03:13 2016
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) xf86OpenConsole: Cannot open virtual console 7 (No such file or directory)
(EE) 
(EE) 
Please consult the Fedora Project support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error
Couldn't get a file descriptor referring to the console

**Comment by nmilosev** [comment]
Hello, thanks for the report!

Updates can break X server, it happened to me as well sadly. Please do the fixes as described in the FAQ section. I will look into how I can make the process automated.

Sorry for the inconvenience. 

Kind regards

**Comment by vlaero** [comment]
OK - I've had a look at the FAQ section.
I checked to see if /usr/libexec/Xorg was different to /usr/bin/Xorg and it was. So, doing the following fixed the issue:
cp /usr/libexec/Xorg /usr/bin/

Will be interested to hear what you come up with in regards to a more robust fix.
Also, the instructions in your FAQ for setting ownership on /tmp is different to what you have in /usr/local/bin/freonx.  Does /tmp need ownership changed or is it just /tmp/crouton-lock ?

**Comment by nmilosev** [comment]
Hey, glad you fixed it! :)

I am unsure if `/tmp` needs to be owned by `1000:1000` user, I will look into it. As you can see it's a pretty nasty hack to run X as non-root user. :(

For the updates fix I think we can do two things, either:
1. exclude everything xorg and mesa related in `dnf.conf` so it doesn't get updated ever, or
2. create a wrapper script around dnf or freonx script which will prompt the user to do the fix when xorg gets an update - this includes making a script which does the fixes automatically

I'm leaning towards 2, what do you think?

Thanks again for the report, and I'm sorry for the inconvenience.

Cheers!
