### ISSUE TITLE
Docker image is pointing to old URL

### ISSUE THREAD

**Issue by J5** [nmilosev/crouton-fedora#6]
I ended up editing the fedora/default script to point to here: https://download.fedoraproject.org/pub/fedora/linux/releases/24/Docker/x86_64/images/Fedora-Docker-Base-24-1.2.x86_64.tar.xz

**Comment by nmilosev** [comment]
Hey J5, thank you for reporting this. Indeed koji links go away quickly.

Were you able to setup crouton-fedora with this link normally? I would like to replace it as a more permanent solution.

Cheers!

**Comment by J5** [comment]
Sorry for not getting back to you but yes. It worked really well.
