### ISSUE TITLE
issues installing freon using sudo, cannot change fedora user password

### ISSUE THREAD

**Issue by mdeguzis** [nmilosev/crouton-fedora#8]
Your readme notes:

```
sudo sh /home/fedora/Downloads/crouton-fedora-master/freon-x/install.sh
```

As fedora user, but the password is not set. `passwd` does not work, command not found.

**Comment by nmilosev** [comment]
Password should be: fedora.

You can use su, root password is fedora, install passwd with dnf and change it. But the default should be fedora. 

Cheers.

**Comment by mdeguzis** [comment]
oh ok, thanks! Can you place this in the readme? maybe I missed it.

**Comment by nmilosev** [comment]
My bad, the script says it when done, but you're right it should be in the readme. I'll update it.

Thanks for reporting the issue.

Cheers!

**Comment by mdeguzis** [comment]
No, thank you so much for putting together this repo and pooling together the steps using the docker image. I was about to almost stop searching for "Crouton fedora" until I found this. This greatly helps me for work. Keep up the great work!
