### ISSUE TITLE
croutoncycle - broken symlink

### ISSUE THREAD

**Issue by mdeguzis** [nmilosev/crouton-fedora#9]
I don't see in code where croutoncycle is installed, so perhaps this is my own issue, but I wanted to be sure. The file in /usr/local/bin does not exist. Is it possible there is a missed install step? 

> How do I switch to Fedora?
> Type croutoncycle :0 to another terminal or press CTRL+ALT+SHIFT+F2.

Broken link (red text)

```
ls -la /bin/croutoncycle
lrwxrwxrwx 1 root root 27 sept 27 13:42 /bin/croutoncycle -> /usr/local/bin/croutoncycle
```

Copying /usr/local/crouton-fedora/chroots/fedora/usr/local/bin/croutoncycle to /usr/local/bin/ seemed to work ok.

**Comment by nmilosev** [comment]
Maybe it is unclear (again), you need to execute `croutoncycle :0` in a crosh shell, not Fedora shell. The binaries are installed with crouton, but I never experienced this issue. Does CTRL+ALT+SHIFT+F2 key combo work?

Also if you used a different path with `-p` parameter the binaries would be installed in that path rather than the default one. Maybe this is the issue?

Cheers.

**Comment by mdeguzis** [comment]
I did use a custom path, that's likely why I had to copy the binary to /usr/local/bin

On September 28, 2016 6:22:07 AM EDT, Nemanja Milosevic notifications@github.com wrote:

> Maybe it is unclear (again), you need to execute `croutoncycle :0`
> in a crosh shell, not Fedora shell. The binaries are installed with
> crouton, but I never experienced this issue. Does CTRL+ALT+SHIFT+F2 key
> combo work?
> 
> Also if you used a different path with `-p` parameter the binaries
> would be installed in that path rather than the default one. Maybe this
> is the issue?
> 
> Cheers.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nmilosev/crouton-fedora/issues/9#issuecomment-250128967

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nmilosev** [comment]
Closing this, since I think this is how Crouton is intended to work. If you use a custom prefix you have to make a symlink manually.
